version: '3'
services:
  db:
    image: postgres
  web:
    build: .
    command: bundle exec rails s -p 80 -b '127.0.0.1'
    volumes:
      - .:/myapp
    ports:
      - "127.0.0.1:80:80"
    depends_on:
      - db