branch-defaults:
  docker-compose:
    environment: Rails-tutorial-sampleapp
    group_suffix: null
environment-defaults:
  Rails-tutorial-sampleapp:
    branch: null
    repository: null
global:
  application_name: profile
  branch: null
  default_ec2_keyname: null
  default_platform: Multi-container Docker 18.03.1-ce (Generic)
  default_region: ap-northeast-1
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: eb-cli
  repository: null
  sc: git
  workspace_type: Application
