branch-defaults:
  docker-compose:
    environment: Rails-tutorial-sampleApp
global:
  application_name: Rails-tutorial-sampleApp
  branch: null
  default_ec2_keyname: Rails-tutorial-SampleApp
  default_platform: docker
  default_region: ap-northeast-1
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: eb-cli
  repository: null
  sc: git
  workspace_type: Application
