version: 2
jobs:
  eb-Rails-tutorial-Sampleapp:
    docker:
      - image: circleci/ruby:2.5

    working_directory: ~/myapp
    
    steps:
      - checkout
      - run:
          name: apt-get update
          command: sudo apt-get -y -qq update
      - run:
          name: Install pip
          command: sudo apt-get install python-pip python-dev build-essential
      - run:
          name: Install awsebcli
          command: sudo pip install awsebcli --upgrade
      - run:
          name: Setup AWS credentials
          command: |
            mkdir ~/.aws && printf "[profile eb-cli]\naws_access_key_id = ${AWS_ACCESS_KEY_ID}\naws_secret_access_key = ${AWS_SECRET_ACCESS_KEY}" > ~/.aws/config
      - run:
          name: eb deploy
          command: eb deploy Rails-tutorial-SampleApp-dev

workflows:
  version: 2
  build-deploy:
    jobs:
      - eb-Rails-tutorial-Sampleapp:
          filters:
            branches:
              only:
                - docker-compose
                - add-CircleCI